[package]
name = "hugind"
version = "0.10.0"
edition = "2024"

[dependencies]
rquickjs = { version = "0.11", features = ["loader", "futures", "classes", "macro"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream", "blocking"] }
libc = "0.2"
serde_json = "1.0"
dirs = "6.0.0"
sysinfo = "0.38.0"
inquire = "0.9.2"
indicatif = "0.18.3"
futures-util = "0.3.31"
chrono = { version = "0.4.43", features = ["serde"] }
uuid = { version = "1.20.0", features = ["v4", "fast-rng"] }
tokio-stream = "0.1.17"
base64 = "0.22.1"
bytes = "1.11.0"
wasmtime = { version = "18.0.2", features = ["async"] }
wasmtime-wasi = "18.0.2"
cap-std = "2.0.2"
encoding_rs = "0.8.35"
axum = "0.7.7"
tempfile = "3.24.0"
zip = "2.2.0"
semver = "1.0"
llama-cpp = { path = "/Users/adel/Workspace/llama_cpp_rust/llama-cpp", features = ["metal", "mtmd"] }
tower = { version = "0.4", features = ["util", "timeout", "limit"] }
tower-http = { version = "0.5", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
parking_lot = "0.12"
thiserror = "2.0.18"
async-stream = "0.3"
futures = "0.3"

[dev-dependencies]
tempfile = "3.24.0"
